import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { SignInButton, useUser } from "@clerk/nextjs";

import { api, type RouterOutputs } from "~/utils/api";

import dayjs from "dayjs";
import relativeTime from 'dayjs/plugin/relativeTime';
import { LoadingBox } from "components/loading";

dayjs.extend(relativeTime);

const PostWizard: React.FC = () => {
  const { user } = useUser();

  console.log("userId", user?.id);

  if (!user) {
    return null;
  }

  return (
    <div className="flex gap-3 w-full">
      <Image
        src={user?.profileImageUrl || "/user-circle.png"}
        alt="Profile image"
        className="rounded-full"
        width={44}
        height={44}
      />
      <input
        placeholder="✨ Type your favorite emojis"
        className="bg-transparent grow outline-none text-xl"
      />
    </div>
  );
};

type PostWithUser = RouterOutputs["post"]["getAll"][number];

const PostView = ({ post, author }: PostWithUser) => {
  return (
    <div
      key={post.id}
      className="p-4 border-b border-gray-500 flex items-center"
    >
      <div className="h-11 w-11">
        <Image
          src={author?.profileImageUrl || "/user-circle.png"}
          width={44}
          height={44}
          alt="Author image"
          className="rounded-full"
        />
      </div>
      <div className="px-4 flex flex-col">
        <div className="fle gap-1">
          <span className="font-normal text-gray-200">{`@${author?.username}`}</span> {" · "}
          <span className="font-normal text-gray-400">{`${dayjs(post?.createdAt).fromNow()}`}</span>
        </div>
        <p>{post.content}</p>
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  const user = useUser();

  const postQuery = api.post.getAll.useQuery();

  if (postQuery.isLoading) {
    return (
      <div className="flex justify-center items-center h-screen twimoji">
        <LoadingBox />
      </div>
    );
  }

  if (!postQuery.data) {
    return (
      <div className="flex justify-center items-center h-screen twimoji">
        Something went wrong.
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>Eventer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-[100dvh] twimoji">
        <div className="container w-full border-gray-500 md:border-x md:max-w-2xl">
          <div className="border-b border-gray-500 p-4 flex">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {!!user.isSignedIn && (
              <div className="flex justify-center grow">
                <PostWizard />
              </div>
            )}
          </div>
          <div className="flex flex-col">
            {postQuery.data?.map((fullPost) => (
              <PostView {...fullPost} key={fullPost?.post.id} />
            ))}
          </div>
          {/* <CreatePostForm /> */}
        </div>
      </main>
    </>
  );
};

export default Home;
